refs 3162 new AbstractConnection infrastructure
qorelanguage/module-ssh2 pull request #82
Opened 2018-12-04 14:53 UTC by pvanek

depending on https://github.com/qorelanguage/qore/pull/3163

2018-12-04 18:27 UTC, davidnich approved these changes
looks fine - just need the Qore changes to be merged to get jenkins passing

2018-12-05 18:01 UTC, sejvlond requested changes

2018-12-05 18:01 UTC, sejvlond commented on qlib/Ssh2Connections.qm
> +        constructor(string name, string desc, string url, bool monitor, *hash opts, hash urlh)
missing deprecated

2018-12-05 18:01 UTC, sejvlond commented on qlib/Ssh2Connections.qm
> +        constructor(string name, string desc, string url, bool monitor, *hash opts, hash urlh)
missing deprecated

2018-12-07 09:59 UTC, sejvlond approved these changes

2018-12-07 10:53 UTC, merged